spring.application.name=student-crud-swagger
spring.datasource.url=jdbc:mysql://localhost:3306/exp16
spring.datasource.username=root
spring.datasource.password=admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080